server:
  port: 9004

custom:
  server-ip: 192.168.29.226

spring:
  config:
    import: "optional:configserver:http://${custom.server-ip}:9009"
  application:
    name: NOTIFICATION-SERVICE
  boot:
    admin:
      client:
        url: http://${custom.server-ip}:8762
        instance:
          service-base-url: http://${custom.server-ip}:${server.port}
          name: ${spring.application.name}
  kafka:
    bootstrap-servers: ${custom.server-ip}:9092
    consumer:
      group-id: ms-notification
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${custom.server-ip}:8761/eureka/
  instance:
    hostname: ${custom.server-ip}
    prefer-ip-address: true
    ip-address: ${custom.server-ip}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    pause:
      enabled: true
    health:
      show-details: always
    info:
      enabled: true
    metrics:
      enabled: true
    env:
      enabled: true