server:
  port: 9004

custom:
  server-ip: 192.168.29.226

spring:
  application:
    name: NOTIFICATION-SERVICE
  kafka:
    bootstrap-servers: ${custom.server-ip}:9092
    consumer:
      group-id: ms-notification
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${custom.server-ip}:8761/eureka/
  instance:
    hostname: ${custom.server-ip}
    prefer-ip-address: true
